CREATE TABLE PUBLIC.DEMOTABLE
    (
        DEPTID   BIGINT IDENTITY(1, 1) NOT NULL
      , DEPTNAME VARCHAR(50) NOT NULL
      , EMPNAME VARCHAR(50) NOT NULL
      , EMPID VARCHAR(50) NOT NULL
      , PARAENTDEPTID BIGINT NOT NULL
    );
