create TABLE PUBLIC.DIM_DATE (
	DATE_ID DATE NOT NULL,
	WEEK_ID NUMBER(38,0),
	FISCAL_WEEK NUMBER(38,0),
	MONTH_NUMBER NUMBER(38,0),
	MONTH VARCHAR(16777216),
	YEAR NUMBER(38,0),
	primary key (DATE_ID)
);
